fetch("/champs.json")
    .then((response) => response.json())
    .then((json) => {
        
        var map = Object.keys(json.data).map((key) => json.data[key])
        
        console.log("map", map)

        const random = Math.floor(Math.random() * map.length)
        
        console.log(map[random])
        console.log(map[random].name)
        console.log(random)
})

console.log("Hello World!")

const map = new Map([
    ["aatrox", {
        name: "Aatrox",
        title: "the Darkin Blade",
        year: 2013,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["ahri", {
        name: "Ahri",
        title: "the Nine-Tailed Fox",
        year: 2011,
        tags: ["Mage", "Assassin"],
        primaryLane: "Mid",
    }],
    ["akali", {
        name: "Akali",
        title: "the Rogue Assassin",
        year: 2010,
        tags: ["Assassin"],
        primaryLane: "Mid",
    }],
    ["alistar", {
        name: "Alistar",
        title: "the Minotaur",
        year: 2009,
        tags: ["Tank", "Support"],
        primaryLane: "Support",
    }],
    ["amumu", {
        name: "Amumu",
        title: "the Sad Mummy",
        year: 2009,
        tags: ["Tank", "Mage"],
        primaryLane: "Jungle",
    }],
    ["anivia", {
        name: "Anivia",
        title: "the Cryophoenix",
        year: 2009,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["annie", {
        name: "Annie",
        title: "the Dark Child",
        year: 2009,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["aphelios", {
        name: "Aphelios",
        title: "the Weapon of the Faithful",
        year: 2019,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["ashe", {
        name: "Ashe",
        title: "the Frost Archer",
        year: 2009,
        tags: ["Marksman", "Support"],
        primaryLane: "Bot",
    }],
    ["aurelionsol", {
        name: "Aurelion Sol",
        title: "The Star Forger",
        year: 2016,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["azir", {
        name: "Azir",
        title: "the Emperor of the Sands",
        year: 2014,
        tags: ["Mage", "Marksman"],
        primaryLane: "Mid",
    }],
    ["bard", {
        name: "Bard",
        title: "the Wandering Caretaker",
        year: 2015,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["blitzcrank", {
        name: "Blitzcrank",
        title: "the Great Steam Golem",
        year: 2009,
        tags: ["Tank", "Support"],
        primaryLane: "Support",
    }],
    ["brand", {
        name: "Brand",
        title: "the Burning Vengeance",
        year: 2011,
        tags: ["Mage"],
        primaryLane: ["Mid", "Support"],
    }],
    ["braum", {
        name: "Braum",
        title: "the Heart of the Freljord",
        year: 2014,
        tags: ["Support", "Tank"],
        primaryLane: "Support",
    }],
    ["caitlyn", {
        name: "Caitlyn",
        title: "the Sheriff of Piltover",
        year: 2011,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["camille", {
        name: "Camille",
        title: "the Steel Shadow",
        year: 2016,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["cassiopeia", {
        name: "Cassiopeia",
        title: "the Serpent's Embrace",
        year: 2010,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["cho'gath", {
        name: "Cho'Gath",
        title: "the Terror of the Void",
        year: 2009,
        tags: ["Tank", "Mage"],
        primaryLane: "Top",
    }],
    ["corki", {
        name: "Corki",
        title: "the Daring Bombardier",
        year: 2009,
        tags: ["Marksman"],
        primaryLane: "Mid",
    }],
    ["darius", {
        name: "Darius",
        title: "the Hand of Noxus",
        year: 2012,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["diana", {
        name: "Diana",
        title: "Scorn of the Moon",
        year: 2012,
        tags: ["Fighter", "Mage"],
        primaryLane: "Mid",
    }],
    ["draven", {
        name: "Draven",
        title: "the Glorious Executioner",
        year: 2012,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["ekko", {
        name: "Ekko",
        title: "the Boy Who Shattered Time",
        year: 2015,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Mid",
    }],
    ["elise", {
        name: "Elise",
        title: "the Spider Queen",
        year: 2012,
        tags: ["Mage", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["evelynn", {
        name: "Evelynn",
        title: "Agony's Embrace",
        year: 2009,
        tags: ["Assassin", "Mage"],
        primaryLane: "Jungle",
    }],
    ["ezreal", {
        name: "Ezreal",
        title: "the Prodigal Explorer",
        year: 2010,
        tags: ["Marksman", "Mage"],
        primaryLane: "Bot",
    }],
    ["fiddlesticks", {
        name: "Fiddlesticks",
        title: "the Ancient Fear",
        year: 2009,
        tags: ["Mage", "Support"],
        primaryLane: "Jungle",
    }],
    ["fiora", {
        name: "Fiora",
        title: "the Grand Duelist",
        year: 2012,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["fizz", {
        name: "Fizz",
        title: "the Tidal Trickster",
        year: 2011,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Mid",
    }],
    ["galio", {
        name: "Galio",
        title: "the Colossus",
        year: 2010,
        tags: ["Tank", "Mage"],
        primaryLane: "Mid",
    }],
    ["gangplank", {
        name: "Gangplank",
        title: "the Saltwater Scourge",
        year: 2009,
        tags: ["Fighter"],
        primaryLane: "Top",
    }],
    ["garen", {
        name: "Garen",
        title: "The Might of Demacia",
        year: 2009,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["gnar", {
        name: "Gnar",
        title: "the Missing Link",
        year: 2014,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["gragas", {
        name: "Gragas",
        title: "the Rabble Rouser",
        year: 2010,
        tags: ["Fighter", "Mage"],
        primaryLane: "Jungle",
    }],
    ["graves", {
        name: "Graves",
        title: "the Outlaw",
        year: 2011,
        tags: ["Marksman", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["hecarim", {
        name: "Hecarim",
        title: "the Shadow of War",
        year: 2012,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["heimerdinger", {
        name: "Heimerdinger",
        title: "the Revered Inventor",
        year: 2009,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["illaoi", {
        name: "Illaoi",
        title: "the Kraken Priestess",
        year: 2015,
        tags: ["Fighter"],
        primaryLane: "Top",
    }],
    ["irelia", {
        name: "Irelia",
        title: "the Blade Dancer",
        year: 2010,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["ivern", {
        name: "Ivern",
        title: "the Green Father",
        year: 2016,
        tags: ["Support", "Mage"],
        primaryLane: "Jungle",
    }],
    ["janna", {
        name: "Janna",
        title: "the Storm's Fury",
        year: 2009,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["jarvaniv", {
        name: "Jarvan IV",
        title: "the Exemplar of Demacia",
        year: 2011,
        tags: ["Tank", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["jax", {
        name: "Jax",
        title: "Grandmaster at Arms",
        year: 2009,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["jayce", {
        name: "Jayce",
        title: "the Defender of Tomorrow",
        year: 2012,
        tags: ["Fighter", "Marksman"],
        primaryLane: "Top",
    }],
    ["jhin", {
        name: "Jhin",
        title: "the Virtuoso",
        year: 2016,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["jinx", {
        name: "Jinx",
        title: "the Loose Cannon",
        year: 2013,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["kaisa", {
        name: "Kai'Sa",
        title: "Daughter of the Void",
        year: 2018,
        tags: ["Marksman", "Assassin"],
        primaryLane: "Bot",
    }],
    ["kalista", {
        name: "Kalista",
        title: "the Spear of Vengeance",
        year: 2014,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["karma", {
        name: "Karma",
        title: "the Enlightened One",
        year: 2011,
        tags: ["Mage", "Support"],
        primaryLane: "Support",
    }],
    ["karthus", {
        name: "Karthus",
        title: "the Deathsinger",
        year: 2009,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["kassadin", {
        name: "Kassadin",
        title: "the Void Walker",
        year: 2009,
        tags: ["Assassin", "Mage"],
        primaryLane: "Mid",
    }],
    ["katarina", {
        name: "Katarina",
        title: "the Sinister Blade",
        year: 2009,
        tags: ["Assassin", "Mage"],
        primaryLane: "Mid",
    }],
    ["kayle", {
        name: "Kayle",
        title: "the Righteous",
        year: 2009,
        tags: ["Fighter", "Support"],
        primaryLane: "Top",
    }],
    ["kayn", {
        name: "Kayn",
        title: "the Shadow Reaper",
        year: 2017,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Jungle",
    }],
    ["kennen", {
        name: "Kennen",
        title: "the Heart of the Tempest",
        year: 2010,
        tags: ["Mage", "Marksman"],
        primaryLane: "Top",
    }],
    ["khazix", {
        name: "Kha'Zix",
        title: "the Voidreaver",
        year: 2012,
        tags: ["Assassin"],
        primaryLane: "Jungle",
    }],
    ["kindred", {
        name: "Kindred",
        title: "The Eternal Hunters",
        year: 2015,
        tags: ["Marksman"],
        primaryLane: "Jungle",
    }],
    ["kled", {
        name: "Kled",
        title: "the Cantankerous Cavalier",
        year: 2016,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["kogmaw", {
        name: "Kog'Maw",
        title: "the Mouth of the Abyss",
        year: 2010,
        tags: ["Marksman", "Mage"],
        primaryLane: "Bot",
    }],
    ["leblanc", {
        name: "LeBlanc",
        title: "the Deceiver",
        year: 2010,
        tags: ["Assassin", "Mage"],
        primaryLane: "Mid",
    }],
    ["leesin", {
        name: "Lee Sin",
        title: "the Blind Monk",
        year: 2011,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Jungle",
    }],
    ["leona", {
        name: "Leona",
        title: "the Radiant Dawn",
        year: 2011,
        tags: ["Tank", "Support"],
        primaryLane: "Support",
    }],
    ["lillia", {
        name: "Lillia",
        title: "the Bashful Bloom",
        year: 2020,
        tags: ["Fighter", "Mage"],
        primaryLane: "Jungle",
    }],
    ["lissandra", {
        name: "Lissandra",
        title: "the Ice Witch",
        year: 2013,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["lucian", {
        name: "Lucian",
        title: "the Purifier",
        year: 2013,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["lulu", {
        name: "Lulu",
        title: "the Fae Sorceress",
        year: 2012,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["lux", {
        name: "Lux",
        title: "the Lady of Luminosity",
        year: 2010,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["malphite", {
        name: "Malphite",
        title: "Shard of the Monolith",
        year: 2009,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["malzahar", {
        name: "Malzahar",
        title: "the Prophet of the Void",
        year: 2010,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["maokai", {
        name: "Maokai",
        title: "the Twisted Treant",
        year: 2011,
        tags: ["Tank", "Mage"],
        primaryLane: "Top",
    }],
    ["masteryi", {
        name: "Master Yi",
        title: "the Wuju Bladesman",
        year: 2009,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["missfortune", {
        name: "Miss Fortune",
        title: "the Bounty Hunter",
        year: 2010,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["mordekaiser", {
        name: "Mordekaiser",
        title: "the Iron Revenant",
        year: 2010,
        tags: ["Fighter", "Mage"],
        primaryLane: "Top",
    }],
    ["morgana", {
        name: "Morgana",
        title: "the Fallen",
        year: 2009,
        tags: ["Mage", "Support"],
        primaryLane: "Support",
    }],
    ["nami", {
        name: "Nami",
        title: "the Tidecaller",
        year: 2012,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["nasus", {
        name: "Nasus",
        title: "the Curator of the Sands",
        year: 2009,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["nautilus", {
        name: "Nautilus",
        title: "the Titan of the Depths",
        year: 2012,
        tags: ["Tank", "Support"],
        primaryLane: "Support",
    }],
    ["neeko", {
        name: "Neeko",
        title: "the Curious Chameleon",
        year: 2018,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["nidalee", {
        name: "Nidalee",
        title: "the Bestial Huntress",
        year: 2009,
        tags: ["Assassin", "Mage"],
        primaryLane: "Jungle",
    }],
    ["nocturne", {
        name: "Nocturne",
        title: "the Eternal Nightmare",
        year: 2011,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["nunu", {
        name: "Nunu & Willump",
        title: "the Boy and His Yeti",
        year: 2009,
        tags: ["Tank", "Support"],
        primaryLane: "Jungle",
    }],
    ["olaf", {
        name: "Olaf",
        title: "the Berserker",
        year: 2010,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["orianna", {
        name: "Orianna",
        title: "the Lady of Clockwork",
        year: 2010,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["ornn", {
        name: "Ornn",
        title: "the Fire below the Mountain",
        year: 2017,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["pantheon", {
        name: "Pantheon",
        title: "the Unbreakable Spear",
        year: 2010,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["poppy", {
        name: "Poppy",
        title: "Keeper of the Hammer",
        year: 2010,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["pyke", {
        name: "Pyke",
        title: "the Bloodharbor Ripper",
        year: 2018,
        tags: ["Support", "Assassin"],
        primaryLane: "Support",
    }],
    ["qiyana", {
        name: "Qiyana",
        title: "Empress of the Elements",
        year: 2019,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Mid",
    }],
    ["quinn", {
        name: "Quinn",
        title: "Demacia's Wings",
        year: 2013,
        tags: ["Marksman", "Fighter"],
        primaryLane: "Top",
    }],
    ["rakan", {
        name: "Rakan",
        title: "The Charmer",
        year: 2017,
        tags: ["Support"],
        primaryLane: "Support",
    }],
    ["rammus", {
        name: "Rammus",
        title: "the Armordillo",
        year: 2009,
        tags: ["Tank", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["rek'sai", {
        name: "Rek'Sai",
        title: "the Void Burrower",
        year: 2014,
        tags: ["Fighter"],
        primaryLane: "Jungle",
    }],
    ["rell", {
        name: "Rell",
        title: "the Iron Maiden",
        year: 2020,
        tags: ["Tank", "Support"],
        primaryLane: "Support",
    }],
    ["renekton", {
        name: "Renekton",
        title: "the Butcher of the Sands",
        year: 2011,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["rengar", {
        name: "Rengar",
        title: "the Pridestalker",
        year: 2012,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["riven", {
        name: "Riven",
        title: "the Exile",
        year: 2011,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["rumble", {
        name: "Rumble",
        title: "the Mechanized Menace",
        year: 2011,
        tags: ["Fighter", "Mage"],
        primaryLane: "Top",
    }],
    ["ryze", {
        name: "Ryze",
        title: "the Rune Mage",
        year: 2009,
        tags: ["Mage", "Fighter"],
        primaryLane: "Mid",
    }],
    ["samira", {
        name: "Samira",
        title: "the Desert Rose",
        year: 2020,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["sejuani", {
        name: "Sejuani",
        title: "Fury of the North",
        year: 2012,
        tags: ["Tank", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["senna", {
        name: "Senna",
        title: "the Redeemer",
        year: 2019,
        tags: ["Marksman", "Support"],
        primaryLane: "Support",
    }],
    ["seraphine", {
        name: "Seraphine",
        title: "the Starry-Eyed Songstress",
        year: 2020,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["sett", {
        name: "Sett",
        title: "the Boss",
        year: 2020,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["shaco", {
        name: "Shaco",
        title: "the Demon Jester",
        year: 2009,
        tags: ["Assassin"],
        primaryLane: "Jungle",
    }],
    ["shen", {
        name: "Shen",
        title: "the Eye of Twilight",
        year: 2010,
        tags: ["Tank", "Support"],
        primaryLane: "Top",
    }],
    ["shyvana", {
        name: "Shyvana",
        title: "the Half-Dragon",
        year: 2011,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["singed", {
        name: "Singed",
        title: "the Mad Chemist",
        year: 2009,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["sion", {
        name: "Sion",
        title: "The Undead Juggernaut",
        year: 2009,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["sivir", {
        name: "Sivir",
        title: "the Battle Mistress",
        year: 2009,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["skarner", {
        name: "Skarner",
        title: "the Crystal Vanguard",
        year: 2011,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["sona", {
        name: "Sona",
        title: "Maven of the Strings",
        year: 2010,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["soraka", {
        name: "Soraka",
        title: "the Starchild",
        year: 2009,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["swain", {
        name: "Swain",
        title: "the Noxian Grand General",
        year: 2010,
        tags: ["Mage", "Tank"],
        primaryLane: "Mid",
    }],
    ["sylas", {
        name: "Sylas",
        title: "the Unshackled",
        year: 2019,
        tags: ["Mage", "Assassin"],
        primaryLane: "Mid",
    }],
    ["syndra", {
        name: "Syndra",
        title: "the Dark Sovereign",
        year: 2012,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["tahmkench", {
        name: "Tahm Kench",
        title: "the River King",
        year: 2015,
        tags: ["Support", "Tank"],
        primaryLane: "Support",
    }],
    ["taliyah", {
        name: "Taliyah",
        title: "the Stoneweaver",
        year: 2016,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["talon", {
        name: "Talon",
        title: "the Blade's Shadow",
        year: 2011,
        tags: ["Assassin"],
        primaryLane: "Mid",
    }],
    ["taric", {
        name: "Taric",
        title: "the Shield of Valoran",
        year: 2009,
        tags: ["Support", "Tank"],
        primaryLane: "Support",
    }],
    ["teemo", {
        name: "Teemo",
        title: "the Swift Scout",
        year: 2009,
        tags: ["Marksman", "Assassin"],
        primaryLane: "Top",
    }],
    ["thresh", {
        name: "Thresh",
        title: "the Chain Warden",
        year: 2013,
        tags: ["Support", "Tank"],
        primaryLane: "Support",
    }],
    ["tristana", {
        name: "Tristana",
        title: "the Yordle Gunner",
        year: 2009,
        tags: ["Marksman", "Assassin"],
        primaryLane: "Bot",
    }],
    ["trundle", {
        name: "Trundle",
        title: "the Troll King",
        year: 2010,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["tryndamere", {
        name: "Tryndamere",
        title: "the Barbarian King",
        year: 2009,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Top",
    }],
    ["twistedfate", {
        name: "Twisted Fate",
        title: "the Card Master",
        year: 2009,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["twitch", {
        name: "Twitch",
        title: "the Plague Rat",
        year: 2009,
        tags: ["Marksman", "Assassin"],
        primaryLane: "Bot",
    }],
    ["udyr", {
        name: "Udyr",
        title: "the Spirit Walker",
        year: 2009,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["urgot", {
        name: "Urgot",
        title: "the Dreadnought",
        year: 2010,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["varus", {
        name: "Varus",
        title: "the Arrow of Retribution",
        year: 2012,
        tags: ["Marksman", "Mage"],
        primaryLane: "Bot",
    }],
    ["vayne", {
        name: "Vayne",
        title: "the Night Hunter",
        year: 2011,
        tags: ["Marksman", "Assassin"],
        primaryLane: "Bot",
    }],
    ["veigar", {
        name: "Veigar",
        title: "the Tiny Master of Evil",
        year: 2009,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["velkoz", {
        name: "Vel'Koz",
        title: "the Eye of the Void",
        year: 2014,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["vex", {
        name: "Vex",
        title: "the Gloomist",
        year: 2021,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["vi", {
        name: "Vi",
        title: "the Piltover Enforcer",
        year: 2012,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["viego", {
        name: "Viego",
        title: "the Ruined King",
        year: 2021,
        tags: ["Assassin", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["viktor", {
        name: "Viktor",
        title: "the Machine Herald",
        year: 2011,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["vladimir", {
        name: "Vladimir",
        title: "the Crimson Reaper",
        year: 2010,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["volibear", {
        name: "Volibear",
        title: "the Relentless Storm",
        year: 2011,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["warwick", {
        name: "Warwick",
        title: "the Uncaged Wrath of Zaun",
        year: 2009,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["wukong", {
        name: "Wukong",
        title: "the Monkey King",
        year: 2011,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["xayah", {
        name: "Xayah",
        title: "the Rebel",
        year: 2017,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["xerath", {
        name: "Xerath",
        title: "the Magus Ascendant",
        year: 2011,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["xinzhao", {
        name: "Xin Zhao",
        title: "the Seneschal of Demacia",
        year: 2010,
        tags: ["Fighter", "Tank"],
        primaryLane: "Jungle",
    }],
    ["yasuo", {
        name: "Yasuo",
        title: "the Unforgiven",
        year: 2013,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Mid",
    }],
    ["yone", {
        name: "Yone",
        title: "the Unforgotten",
        year: 2020,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Mid",
    }],
    ["yorick", {
        name: "Yorick",
        title: "Shepherd of Souls",
        year: 2011,
        tags: ["Fighter", "Tank"],
        primaryLane: "Top",
    }],
    ["yuumi", {
        name: "Yuumi",
        title: "the Magical Cat",
        year: 2019,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["zac", {
        name: "Zac",
        title: "the Secret Weapon",
        year: 2013,
        tags: ["Tank", "Fighter"],
        primaryLane: "Jungle",
    }],
    ["zed", {
        name: "Zed",
        title: "the Master of Shadows",
        year: 2012,
        tags: ["Assassin"],
        primaryLane: "Mid",
    }],
    ["zeri", {
        name: "Zeri",
        title: "the Spark of Zaun",
        year: 2022,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["ziggs", {
        name: "Ziggs",
        title: "the Hexplosives Expert",
        year: 2012,
        tags: ["Mage"],
        primaryLane: "Mid",
    }],
    ["zilean", {
        name: "Zilean",
        title: "the Chronokeeper",
        year: 2009,
        tags: ["Support", "Mage"],
        primaryLane: "Support",
    }],
    ["zoe", {
        name: "Zoe",
        title: "the Aspect of Twilight",
        year: 2017,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }],
    ["zyra", {
        name: "Zyra",
        title: "Rise of the Thorns",
        year: 2012,
        tags: ["Mage", "Support"],
        primaryLane: "Support",
    }],
    ["gwen", {
        name: "Gwen",
        title: "The Hallowed Seamstress",
        year: 2021,
        tags: ["Fighter"],
        primaryLane: "Top",
    }],
    ["akshan", {
        name: "Akshan",
        title: "The Rogue Sentinel",
        year: 2021,
        tags: ["Marksman", "Assassin"],
        primaryLane: "Mid",
    }],
    ["zeri", {
        name: "Zeri",
        title: "The Spark of Zaun",
        year: 2022,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["renata", {
        name: "Renata Glasc",
        title: "The Chem-Baroness",
        year: 2022,
        tags: ["Support"],
        primaryLane: "Support",
    }],
    ["belveth", {
        name: "Bel'Veth",
        title: "The Empress of the Void",
        year: 2022,
        tags: ["Fighter"],
        primaryLane: "Jungle",
    }],
    ["nilah", {
        name: "Nilah",
        title: "The Joy Unbound",
        year: 2022,
        tags: ["Marksman"],
        primaryLane: "Bot",
    }],
    ["ksante", {
        name: "K'Sante",
        title: "The Pride of Nazumah",
        year: 2022,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["milio", {
        name: "Milio",
        title: "The Gentle Flame",
        year: 2023,
        tags: ["Support"],
        primaryLane: "Support",
    }],
    ["naafiri", {
        name: "Naafiri",
        title: "The Hound of a Hundred Bites",
        year: 2023,
        tags: ["Assassin"],
        primaryLane: "Mid",
    }],
    ["briar", {
        name: "Briar",
        title: "The Restrained Hunger",
        year: 2023,
        tags: ["Fighter", "Assassin"],
        primaryLane: "Jungle",
    }],
    ["hwei", {
        name: "Hwei",
        title: "The Wandering Blade",
        year: 2024,
        tags: ["Fighter"],
        primaryLane: "Mid",
    }],
    ["smolder", {
        name: "Smolder",
        title: "The Ember of Vengeance",
        year: 2024,
        tags: ["Mage"],
        primaryLane: "Bot",
    }],
    ["aurora", {
        name: "Aurora",
        title: "The Shimmering Light",
        year: 2024,
        tags: ["Support", "Mage"],
        primaryLane: "Mid",
    }],
    ["ambessa", {
        name: "Ambessa",
        title: "The Iron Matron",
        year: 2024,
        tags: ["Tank", "Fighter"],
        primaryLane: "Top",
    }],
    ["mel", {
        name: "Mel",
        title: "The Golden Strategist",
        year: 2024,
        tags: ["Mage", "Support"],
        primaryLane: "Mid",
    }]
]);


